# Generated by Django 2.1.7 on 2019-11-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uziya_api', '0002_actiontoken_temporarytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreed_terms_use',
            field=models.BooleanField(default=False, verbose_name='Term use'),
        ),
    ]
